// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0a-U32J3McT7ODrpWzPLKlyg_v2tQZ3c',
    appId: '1:801042705511:web:cad6ee8f8a0b6c83ffb8c2',
    messagingSenderId: '801042705511',
    projectId: 'edumate-682e5',
    authDomain: 'edumate-682e5.firebaseapp.com',
    storageBucket: 'edumate-682e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5_nQmk3Ggb-KDLvjoit2v8iNlBrU77c',
    appId: '1:801042705511:android:572f63a2a05922b0ffb8c2',
    messagingSenderId: '801042705511',
    projectId: 'edumate-682e5',
    storageBucket: 'edumate-682e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJF6PP_mPUoTsvTTqQFiiG4Sq2BDXWmE',
    appId: '1:801042705511:ios:0f74784203307cf2ffb8c2',
    messagingSenderId: '801042705511',
    projectId: 'edumate-682e5',
    storageBucket: 'edumate-682e5.appspot.com',
    iosClientId: '801042705511-69mdnl6nlogl3h1e05dvnspvg20vqcu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJF6PP_mPUoTsvTTqQFiiG4Sq2BDXWmE',
    appId: '1:801042705511:ios:0f74784203307cf2ffb8c2',
    messagingSenderId: '801042705511',
    projectId: 'edumate-682e5',
    storageBucket: 'edumate-682e5.appspot.com',
    iosClientId: '801042705511-69mdnl6nlogl3h1e05dvnspvg20vqcu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
